name: apigratis_sdk_flutter
description: A ideia desse SDK é otimizar o tempo de código dos usuários auxiliando na integração com a plataforma.
version: 0.0.9
repository: https://github.com/jhowbhz/apigratis-sdk-flutter

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^1.2.2
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.1.2
  json_serializable: ^6.0.1
