name: apigratis_sdk_flutter
description: SDK oficial Dart/Flutter da plataforma APIBrasil — WhatsApp, SMS, consultas CPF/CNPJ, veículos, CEP, correios, pagamentos PIX/boleto e mais.
version: 0.1.0
homepage: https://apibrasil.io
repository: https://github.com/jhowbhz/apigratis-sdk-flutter
issue_tracker: https://github.com/jhowbhz/apigratis-sdk-flutter/issues
documentation: https://doc.apibrasil.io

topics:
  - apibrasil
  - whatsapp
  - cep
  - cpf-cnpj
  - pix

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.2.2
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
